### ISSUE TITLE
When installing more than one AEM instance, Puppet fails with duplicate declaration of OSGi pid

### ISSUE THREAD

**Issue by henrykuijpers** [bstopp/puppet-aem#88]
I.e. I try to set up an author & publish on the same machine, and configure for example the Sling DavEx Servlet on both the instances.

It does work if I use "DavEx-Author": { "pid": "pid", "properties": { ... } } & "DavEx-Publish": { "pid": "pid", "properties": { ... } }
But to me it feels unneccessary that it has to be like this.

**Comment by bstopp** [comment]
This is required. A Puppet resource has a unique *title*. That resource defines state; since the resource would be tied to either the _Author_ or the _Publish_ it can't distinguish between them without changing state.

**Comment by henrykuijpers** [comment]
Thanks!

**Comment by henrykuijpers** [comment]
@bstopp What if we take into account, next to the PID of the OSGi config, a certain aspect that makes the instance on the machine unique?

I.e. we check with the OSGi PID + port number
Or OSGi PID + home dir

Then we would be able to define OSGi configurations in the normal way.

The properties-approach feels kind of hacky to me; And what if I have a config that contains a 'properties'-property?

**Comment by bstopp** [comment]
>  What if we take into account, next to the PID of the OSGi config, a certain aspect that makes the instance on the machine unique?

The _home_ property of the resource identifies a unique AEM instance. (Note: This is likely to change in v3 of this module).

> Then we would be able to define OSGi configurations in the normal way.

Not sure what you mean when you refer to `normal`. This module is not failing to build when you have non-unique resources. The error you are seeing is Puppet being unable to create a catalog since you are not defining a unique set of resource names so it can create it's state.

> The properties-approach feels kind of hacky to me; 

if you mean that there is a `properties` property to manage the state of the OSGi config; i don't see how this is "hacky". OSGi resources have arbitrary properties. It would be impossible to create what may be thought of as 'pristine' OSGi management resource without creating a unique puppet type for each configurable service in AEM. If you find yourself repeating configs to support such things, i would recommend creating [custom profiles](http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-2/) that wrap this OSGi resource, to make it easier for your needs.

> And what if I have a config that contains a 'properties'-property?

Are you asking what happens if you have an OSGi config that has a configuration named "properties"? Then the structure would look like:
~~~puppet
$cfgs = {
  'properties' => [ 'your', 'data', 'goes', 'here']
}

aem::osgi::config { 'osgi-service-pid' :
  ensure         => present,
  properties     => $cfgs,
  handle_missing => 'remove',
  home           => '/opt/aem/author',
  password       => 'admin',
  type           => 'console',
  username       => 'admin',
~~~

Though if you ask me, your OSGi Service/Component needs a better naming convention defined.
